Kevin/404
IndivisibleSomerville/its-our-call pull request #64
Opened 2018-07-24 00:01 UTC by thekevinscott

Questions/comments:

* Do we have integration tests? If so, should I add one for a 404 page?
* I believe in a `<Switch />` we can get away with just `<Route component={pages.MissingPage404} />` but correct me if wrong
* How do we feel about flexbox in CSS?
* I ran into a type issue out of the gate and a parseInt missing radix error. I've fixed those in the branch but if there's some other way around those errors let me know.

How much fidelity are we looking for in the translation from Invision to code? For instance, I notice the headers differ between the App and Invision, and the font weights specified don't seem to be there (looks like it's just `normal` and `bold`):

In code:
<img width="401" alt="screen shot 2018-07-23 at 19 59 52" src="https://user-images.githubusercontent.com/151596/43109109-118d2e16-8eb3-11e8-9b78-91f2a2ce6876.png">

In Invision:
<img width="401" alt="screen shot 2018-07-23 at 20 00 47" src="https://user-images.githubusercontent.com/151596/43109117-1b2ef8c8-8eb3-11e8-9fcf-0fd53cf68a66.png">

2018-08-03 01:11 UTC, thekevinscott commented
I've updated this PR to not rely on flexbox.

I'm not sure the best way to get true vertical centering without it and would love input. It looks like the parent containers are not set to 100%, so I hard coded a margin on the `h1` that works reasonably well for iphone 6/7/8 in Chrome. But it won't always be centered for every layout, let alone tablet/desktop.

Thoughts?

2018-08-03 18:41 UTC, andrewtremblay commented
@thekevinscott Unless Becca told you otherwise I don't think we need true vertical centering here, just adequate margins to display the 404 in a generally central place. As for non-flexbox solutions: `transform: translateY(-50%);` gets you most of the way towards vertical centering (though mileage may vary). 

As for adhering to the designs, I've kept it close as possible but it doesn't have to be religiously followed. For example, new font weights, (when found), should be added, but pixel perfection should be a low priority.  A final evaluation before it goes live will probably be done by Stacy and/or Becca, that's when the pixels can be pushed around.

2018-08-03 18:48 UTC, andrewtremblay commented on frontend/its-our-call/src/pages/IssueView.tsx
> +    let percentYea = hashed.percentYea ? Number.parseInt(hashed.percentYea, 10) : 55;
Good catch here, I forgot that the radix param is not 10 by default in all implementations.

2018-08-03 19:06 UTC, andrewtremblay requested changes
LG2me, just change the css units to relative ones (or convince me otherwise).

2018-08-03 19:06 UTC, andrewtremblay commented on frontend/its-our-call/src/pages/MissingPage404.css
> +  font-family: 'Montserrat', sans-serif;
font-family is already defined in App.css, not sure if it's needed again here.

2018-08-03 19:06 UTC, andrewtremblay commented on frontend/its-our-call/src/pages/MissingPage404.css
> +  font-size: 26px;
We've been using relative units (mostly `rem`) as the primary units, with minimal need for `px`. I have a similar opinion to the writer of this gist: https://gist.github.com/basham/2175a16ab7c60ce8e001 (However, I can probably be convinced away from this if there's some special case here.)

2018-08-03 19:06 UTC, andrewtremblay commented on frontend/its-our-call/src/@types/react-tiny-popover/index.d.ts
> -      arrowColor?: React.CSSWideKeyword | any;
Ah, you caught my scratchwork, committed accidentally.

2018-09-20 14:53 UTC, thekevinscott commented
My apologies for taking so long to address these comments! 

* font-family is removed, you're right that it was not necessary
* I'm not sure if there's standard definitions for the various `rem` values? I've eyeballed it to be equivalent to `26px` but feel free to change if I screwed this up

2022-07-24 15:10 UTC, closed without merging